// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARyA4dPsz9NzsvIznkMSvak3TxHRpGQsY',
    appId: '1:765443305787:web:4ea442f7d24ca99d11471e',
    messagingSenderId: '765443305787',
    projectId: 'mentorproject-4cb73',
    authDomain: 'mentorproject-4cb73.firebaseapp.com',
    storageBucket: 'mentorproject-4cb73.appspot.com',
    measurementId: 'G-RQ18NRM6VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn-V2Xz1dXPEXi41nLhCCAfrs9zrrkk-w',
    appId: '1:765443305787:android:8206b6c428730e3511471e',
    messagingSenderId: '765443305787',
    projectId: 'mentorproject-4cb73',
    storageBucket: 'mentorproject-4cb73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlGdH28Q9e8kairrsfQ4W96GwbcYDYJbk',
    appId: '1:765443305787:ios:ddc8e00ba561fa8c11471e',
    messagingSenderId: '765443305787',
    projectId: 'mentorproject-4cb73',
    storageBucket: 'mentorproject-4cb73.appspot.com',
    iosBundleId: 'com.example.mentorproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlGdH28Q9e8kairrsfQ4W96GwbcYDYJbk',
    appId: '1:765443305787:ios:ddc8e00ba561fa8c11471e',
    messagingSenderId: '765443305787',
    projectId: 'mentorproject-4cb73',
    storageBucket: 'mentorproject-4cb73.appspot.com',
    iosBundleId: 'com.example.mentorproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARyA4dPsz9NzsvIznkMSvak3TxHRpGQsY',
    appId: '1:765443305787:web:95d6162f4965720511471e',
    messagingSenderId: '765443305787',
    projectId: 'mentorproject-4cb73',
    authDomain: 'mentorproject-4cb73.firebaseapp.com',
    storageBucket: 'mentorproject-4cb73.appspot.com',
    measurementId: 'G-W47279ST7Y',
  );
}
